name: robot
channels:
  - conda-forge
  - nvidia
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.15.3
  - backports.zstd=1.3.0
  - blas=1.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - cpython=3.11.14
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=13.1.115
  - cuda-runtime=12.4.1
  - cuda-version=13.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - double-conversion=3.4.0
  - ffmpeg=4.4.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.3.2
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - intel-openmp=2022.1.0
  - jinja2=3.1.6
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.8
  - libclang13=21.1.8
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.16.1.26
  - libcups=2.3.3
  - libcurand=10.4.1.81
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libllvm21=21.1.8
  - liblzma=5.8.2
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvfatbin=13.1.115
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=18.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libvpx=1.11.0
  - libvulkan-loader=1.4.328.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nettle=3.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.1.1
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - pcre2=10.47
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pyside6=6.10.1
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - qhull=2020.2
  - qt6-main=6.10.1
  - readline=8.3
  - setuptools=80.10.1
  - six=1.17.0
  - tk=8.6.13
  - tzdata=2025c
  - unicodedata2=17.0.0
  - urllib3=2.6.3
  - wayland=1.24.0
  - wheel=0.46.3
  - x264=1!161.3030
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - yaml=0.2.5
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - aioboto3==15.1.0
      - aiobotocore==2.24.0
      - aiodns==3.1.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aioitertools==0.11.0
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - anytree==2.13.0
      - asteval==1.0.6
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.1.0
      - awscrt==0.23.8
      - azure-core==1.28.0
      - azure-identity==1.13.0
      - azure-storage-blob==12.17.0
      - boto3==1.39.11
      - botocore==1.39.11
      - cffi==2.0.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.1.2
      - cmeel==0.59.0
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.83.0
      - cmeel-console-bridge==1.0.2.3
      - cmeel-octomap==1.10.0
      - cmeel-qhull==8.0.2.1
      - cmeel-tinyxml==2.6.2.3
      - cmeel-urdfdom==3.1.1.1
      - cmeel-zlib==1.3.1
      - comm==0.2.3
      - contourpy==1.3.1
      - coverage==7.4.4
      - cryptography==44.0.0
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.2.2
      - cycler==0.11.0
      - daqp==0.7.2
      - decorator==5.2.1
      - dex-retargeting==0.4.6
      - egl-probe==1.0.2
      - eigenpy==3.5.1
      - einops==0.8.2
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fastapi==0.115.7
      - filelock==3.13.1
      - flaky==3.8.1
      - flatdict==4.0.1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.76.0
      - gunicorn==23.0.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - gymnasium==1.2.1
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hidapi==0.14.0.post2
      - hpp-fcl==2.4.4
      - httpcore==1.0.9
      - httptools==0.6.1
      - httpx==0.28.1
      - huggingface-hub==1.3.4
      - hydra-core==1.3.2
      - idna==3.10
      - idna-ssl==1.1.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - ipython==9.9.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - isaaclab==0.54.1
      - isaaclab-assets==0.2.4
      - isaaclab-contrib==0.0.1
      - isaaclab-mimic==1.0.16
      - isaaclab-rl==0.4.7
      - isaaclab-tasks==0.11.12
      - isaacsim==5.1.0.0
      - isaacsim-benchmark==5.1.0.0
      - isaacsim-core==5.1.0.0
      - isaacsim-gui==5.1.0.0
      - isaacsim-kernel==5.1.0.0
      - isaacsim-rl==5.1.0.0
      - isaacsim-robot==5.1.0.0
      - isaacsim-robot-motion==5.1.0.0
      - isaacsim-sensor==5.1.0.0
      - isaacsim-storage==5.1.0.0
      - isaacsim-utils==5.1.0.0
      - isodate==0.6.1
      - jedi==0.19.2
      - jmespath==1.0.1
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - junitparser==4.0.2
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.4
      - llvmlite==0.42.0
      - loop-rate-limiters==1.2.0
      - lxml==6.0.2
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.3
      - matplotlib==3.10.3
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - moviepy==2.2.1
      - msal==1.27.0
      - msal-extensions==1.0.0
      - msgpack==1.1.2
      - multidict==6.1.0
      - nest-asyncio==1.5.6
      - networkx==3.3
      - nlopt==2.7.1
      - numba==0.59.1
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.55
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnx==1.20.1
      - onnx-ir==0.1.15
      - onnxscript==0.5.7
      - opencv-python==4.13.0.90
      - opencv-python-headless==4.11.0.86
      - orjson==3.11.5
      - osqp==0.6.7.post3
      - packaging==23.0
      - pandas==3.0.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - pin==2.7.0
      - pin-pink==3.1.0
      - pint==0.20.1
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - portalocker==2.7.0
      - prettytable==3.3.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - propcache==0.2.1
      - protobuf==6.33.4
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycares==4.8.0
      - pycparser==3.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pyglet==1.5.31
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pyparsing==3.0.9
      - pyperclip==1.8.0
      - pypng==0.20220715.0
      - pytest==9.0.2
      - pytest-mock==3.15.1
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytransform3d==3.14.4
      - pytz==2024.1
      - pyvers==0.2.2
      - pyyaml==6.0.2
      - qdldl==0.1.7.post5
      - qpsolvers==4.8.2
      - qrcode==7.4.2
      - quadprog==0.1.13
      - ray==2.52.1
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - rich==14.3.1
      - rl-games==1.6.1
      - robomimic==0.4.0
      - rpds-py==0.30.0
      - rsl-rl-lib==3.1.0
      - rtree==1.3.0
      - ruamel-yaml==0.19.1
      - rwm-ur5e==0.1.0
      - s3transfer==0.13.1
      - safetensors==0.7.0
      - scipy==1.15.3
      - sentry-sdk==2.29.1
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - skrl==1.4.3
      - smmap==5.0.2
      - stable-baselines3==2.7.1
      - stack-data==0.6.3
      - starlette==0.49.1
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensordict==0.11.0
      - termcolor==3.3.0
      - timm==1.0.24
      - tokenizers==0.22.2
      - toml==0.10.2
      - tomli==2.4.0
      - torch==2.7.0+cu128
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==5.0.0
      - trimesh==4.5.1
      - triton==3.3.0
      - typer-slim==0.21.1
      - typing-extensions==4.12.2
      - typing-inspection==0.4.2
      - uvicorn==0.29.0
      - wandb==0.24.0
      - warp-lang==1.11.0
      - watchdog==4.0.0
      - wcwidth==0.5.0
      - websockets==12.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - wrapt==1.16.0
      - yarl==1.18.3
      - zipp==3.23.0
prefix: /home/raghav/miniconda3/envs/robot
